// DHL Express countries: the 234 codes and names of the "country" sheet of DHL's reference
// data (ExpressReferenceData_2026-09-06.xlsx), as pinned in functions/shipping/dhl/contract-snapshot.json.
// Generated from that file; do not edit by hand. Some codes are DHL's own, not ISO (XB, XC, XE, XM,
// XN, XS, XY, KV, IC), which is why the list is DHL's and not the browser's.
//
// A name is shown in the app's language where the browser knows the region (Intl.DisplayNames), and
// DHL's name otherwise.

export const DHL_COUNTRIES: ReadonlyArray<readonly [string, string]> = [
  ["AD", "Andorra"],
  ["AE", "United Arab Emirates"],
  ["AF", "Afghanistan"],
  ["AG", "Antigua"],
  ["AI", "Anguilla"],
  ["AL", "Albania"],
  ["AM", "Armenia"],
  ["AO", "Angola"],
  ["AR", "Argentina"],
  ["AS", "American Samoa"],
  ["AT", "Austria"],
  ["AU", "Australia"],
  ["AW", "Aruba"],
  ["AZ", "Azerbaijan"],
  ["BA", "Bosnia And Herzegovina"],
  ["BB", "Barbados"],
  ["BD", "Bangladesh"],
  ["BE", "Belgium"],
  ["BF", "Burkina Faso"],
  ["BG", "Bulgaria"],
  ["BH", "Bahrain"],
  ["BI", "Burundi"],
  ["BJ", "Benin"],
  ["BM", "Bermuda"],
  ["BN", "Brunei"],
  ["BO", "Bolivia"],
  ["BR", "Brazil"],
  ["BS", "Bahamas"],
  ["BT", "Bhutan"],
  ["BW", "Botswana"],
  ["BY", "Belarus"],
  ["BZ", "Belize"],
  ["CA", "Canada"],
  ["CD", "Congo, The Democratic Republic Of"],
  ["CF", "Central African Republic"],
  ["CG", "Congo"],
  ["CH", "Switzerland"],
  ["CI", "Cote D Ivoire"],
  ["CK", "Cook Islands"],
  ["CL", "Chile"],
  ["CM", "Cameroon"],
  ["CN", "The People's Republic Of China"],
  ["CO", "Colombia"],
  ["CR", "Costa Rica"],
  ["CU", "Cuba"],
  ["CV", "Cape Verde"],
  ["CY", "Cyprus"],
  ["CZ", "Czech Republic, The"],
  ["DE", "Germany"],
  ["DJ", "Djibouti"],
  ["DK", "Denmark"],
  ["DM", "Dominica"],
  ["DO", "Dominican Republic"],
  ["DZ", "Algeria"],
  ["EC", "Ecuador"],
  ["EE", "Estonia"],
  ["EG", "Egypt"],
  ["ER", "Eritrea"],
  ["ES", "Spain"],
  ["ET", "Ethiopia"],
  ["FI", "Finland"],
  ["FJ", "Fiji"],
  ["FK", "Falkland Islands"],
  ["FM", "Micronesia, Federated States Of"],
  ["FO", "Faroe Islands"],
  ["FR", "France"],
  ["GA", "Gabon"],
  ["GB", "United Kingdom"],
  ["GD", "Grenada"],
  ["GE", "Georgia"],
  ["GF", "French Guyana"],
  ["GG", "Guernsey"],
  ["GH", "Ghana"],
  ["GI", "Gibraltar"],
  ["GL", "Greenland"],
  ["GM", "Gambia"],
  ["GN", "Guinea Republic"],
  ["GP", "Guadeloupe"],
  ["GQ", "Guinea-Equatorial"],
  ["GR", "Greece"],
  ["GT", "Guatemala"],
  ["GU", "Guam"],
  ["GW", "Guinea-Bissau"],
  ["GY", "Guyana (British)"],
  ["HK", "Hong Kong Sar, China"],
  ["HN", "Honduras"],
  ["HR", "Croatia"],
  ["HT", "Haiti"],
  ["HU", "Hungary"],
  ["IC", "Canary Islands, The"],
  ["ID", "Indonesia"],
  ["IE", "Ireland, Republic Of"],
  ["IL", "Israel"],
  ["IN", "India"],
  ["IQ", "Iraq"],
  ["IR", "Iran (Islamic Republic Of)"],
  ["IS", "Iceland"],
  ["IT", "Italy"],
  ["JE", "Jersey"],
  ["JM", "Jamaica"],
  ["JO", "Jordan"],
  ["JP", "Japan"],
  ["KE", "Kenya"],
  ["KG", "Kyrgyzstan"],
  ["KH", "Cambodia"],
  ["KI", "Kiribati"],
  ["KM", "Comoros"],
  ["KN", "St. Kitts"],
  ["KP", "Korea, The D.P.R Of (North K.)"],
  ["KR", "Korea, Republic Of (South K.)"],
  ["KV", "Kosovo"],
  ["KW", "Kuwait"],
  ["KY", "Cayman Islands"],
  ["KZ", "Kazakhstan"],
  ["LA", "Lao Peoples Democratic Republic"],
  ["LB", "Lebanon"],
  ["LC", "St. Lucia"],
  ["LI", "Liechtenstein"],
  ["LK", "Sri Lanka"],
  ["LR", "Liberia"],
  ["LS", "Lesotho"],
  ["LT", "Lithuania"],
  ["LU", "Luxembourg"],
  ["LV", "Latvia"],
  ["LY", "Libya"],
  ["MA", "Morocco"],
  ["MC", "Monaco"],
  ["MD", "Moldova, Republic Of"],
  ["ME", "Montenegro, Republic Of"],
  ["MG", "Madagascar"],
  ["MH", "Marshall Islands"],
  ["MK", "North Macedonia"],
  ["ML", "Mali"],
  ["MM", "Myanmar"],
  ["MN", "Mongolia"],
  ["MO", "Macao Sar, China"],
  ["MP", "Commonwealth No. Mariana Islands"],
  ["MQ", "Martinique"],
  ["MR", "Mauritania"],
  ["MS", "Montserrat"],
  ["MT", "Malta"],
  ["MU", "Mauritius"],
  ["MV", "Maldives"],
  ["MW", "Malawi"],
  ["MX", "Mexico"],
  ["MY", "Malaysia"],
  ["MZ", "Mozambique"],
  ["NA", "Namibia"],
  ["NC", "New Caledonia"],
  ["NE", "Niger"],
  ["NG", "Nigeria"],
  ["NI", "Nicaragua"],
  ["NL", "Netherlands, The"],
  ["NO", "Norway"],
  ["NP", "Nepal"],
  ["NR", "Nauru, Republic Of"],
  ["NU", "Niue"],
  ["NZ", "New Zealand"],
  ["OM", "Oman"],
  ["PA", "Panama"],
  ["PE", "Peru"],
  ["PF", "Tahiti"],
  ["PG", "Papua New Guinea"],
  ["PH", "Philippines, The"],
  ["PK", "Pakistan"],
  ["PL", "Poland"],
  ["PR", "Puerto Rico"],
  ["PT", "Portugal"],
  ["PW", "Palau"],
  ["PY", "Paraguay"],
  ["QA", "Qatar"],
  ["RE", "Reunion, Island Of"],
  ["RO", "Romania"],
  ["RS", "Serbia, Republic Of"],
  ["RU", "Russian Federation, The"],
  ["RW", "Rwanda"],
  ["SA", "Saudi Arabia"],
  ["SB", "Solomon Islands"],
  ["SC", "Seychelles"],
  ["SD", "Sudan"],
  ["SE", "Sweden"],
  ["SG", "Singapore"],
  ["SH", "Saint Helena"],
  ["SI", "Slovenia"],
  ["SK", "Slovakia"],
  ["SL", "Sierra Leone"],
  ["SM", "San Marino"],
  ["SN", "Senegal"],
  ["SO", "Somalia Mogadishu"],
  ["SR", "Suriname"],
  ["SS", "South Sudan"],
  ["ST", "Sao Tome And Principe"],
  ["SV", "El Salvador"],
  ["SY", "Syria"],
  ["SZ", "Eswatini"],
  ["TC", "Turks And Caicos Islands"],
  ["TD", "Chad"],
  ["TG", "Togo"],
  ["TH", "Thailand"],
  ["TJ", "Tajikistan"],
  ["TL", "Timor Leste"],
  ["TM", "Turkmenistan"],
  ["TN", "Tunisia"],
  ["TO", "Tonga"],
  ["TR", "Turkey"],
  ["TT", "Trinidad And Tobago"],
  ["TV", "Tuvalu"],
  ["TW", "Taiwan"],
  ["TZ", "Tanzania"],
  ["UA", "Ukraine"],
  ["UG", "Uganda"],
  ["US", "United States Of America"],
  ["UY", "Uruguay"],
  ["UZ", "Uzbekistan"],
  ["VA", "Vatican City State"],
  ["VC", "St. Vincent"],
  ["VE", "Venezuela"],
  ["VG", "Virgin Islands (British)"],
  ["VI", "Virgin Islands (Us)"],
  ["VN", "Vietnam"],
  ["VU", "Vanuatu"],
  ["WS", "Samoa"],
  ["XB", "Bonaire"],
  ["XC", "Curacao"],
  ["XE", "St. Eustatius"],
  ["XM", "St. Maarten"],
  ["XN", "Nevis"],
  ["XS", "Somalia Hargeisa"],
  ["XY", "St. Barthelemy"],
  ["YE", "Yemen, Republic Of"],
  ["YT", "Mayotte"],
  ["ZA", "South Africa"],
  ["ZM", "Zambia"],
  ["ZW", "Zimbabwe"]
];

export function dhlCountryName(code: string, locale: string): string {
  const upper = String(code || "").toUpperCase();
  const row = DHL_COUNTRIES.find(([c]) => c === upper);
  if (!row) return upper;
  // DHL's own codes XB, XC, XE, XM, XN, XS and XY sit in ISO's user-assigned X range, where the
  // browser's region names mean something else: XB is "Pseudo-Bidi" there, and Bonaire could not be
  // found by its name. Those are always DHL's name.
  if (upper.startsWith("X")) return row[1];
  try {
    const localized = new Intl.DisplayNames([locale], { type: "region" }).of(upper);
    if (localized && localized !== upper) return localized;
  } catch {
    // An unknown locale or region code: DHL's name below.
  }
  return row[1];
}
