// "Send the tracking details to the customer by e-mail?" (web, 8 Oct 2026): the words of
// app/orders/OrderTrackingEmailSection.tsx and app/orders/TrackingEmailDialog.tsx in the eleven
// languages the rest of the app speaks. Every key is new to the app; nothing the app already
// says is changed. {to}, {at} and {error} are filled in after translation and must survive it.
// NivaDesk and 17TRACK stay as they are in every language.
import type { StudioLanguage } from "./language";

type Row = Partial<Record<StudioLanguage, string>>;

export const TRACKING_EMAIL_TRANSLATIONS: Record<string, Row> = {
  "Send the tracking details to the customer by e-mail?": {"Türkçe": "Takip bilgileri müşteriye e-postayla gönderilsin mi?", "Deutsch": "Sendungsdaten per E-Mail an den Kunden senden?", "Français": "Envoyer les informations de suivi au client par e-mail ?", "Italiano": "Inviare i dettagli di tracciamento al cliente via e-mail?", "Español (Spanish)": "¿Enviar los datos de seguimiento al cliente por correo electrónico?", "Português": "Enviar os dados de rastreio ao cliente por e-mail?", "Русский (Russian)": "Отправить клиенту данные для отслеживания по электронной почте?", "日本語 (Japanese)": "追跡情報をメールでお客様に送信しますか？", "中文 (Chinese)": "是否通过电子邮件将追踪信息发送给客户？", "العربية (Arabic)": "هل تريد إرسال بيانات التتبع إلى العميل بالبريد الإلكتروني؟", "हिन्दी (Hindi)": "ट्रैकिंग जानकारी ग्राहक को ई-मेल से भेजें?"},
  "Yes, prepare the e-mail": {"Türkçe": "Evet, e-postayı hazırla", "Deutsch": "Ja, E-Mail vorbereiten", "Français": "Oui, préparer l'e-mail", "Italiano": "Sì, prepara l'e-mail", "Español (Spanish)": "Sí, preparar el correo", "Português": "Sim, preparar o e-mail", "Русский (Russian)": "Да, подготовить письмо", "日本語 (Japanese)": "はい、メールを準備する", "中文 (Chinese)": "是，准备邮件", "العربية (Arabic)": "نعم، جهّز الرسالة", "हिन्दी (Hindi)": "हाँ, ई-मेल तैयार करें"},
  "Resend": {"Türkçe": "Yeniden gönder", "Deutsch": "Erneut senden", "Français": "Renvoyer", "Italiano": "Invia di nuovo", "Español (Spanish)": "Reenviar", "Português": "Reenviar", "Русский (Russian)": "Отправить повторно", "日本語 (Japanese)": "再送信", "中文 (Chinese)": "重新发送", "العربية (Arabic)": "إعادة الإرسال", "हिन्दी (Hindi)": "फिर से भेजें"},
  "E-mail tracking details": {"Türkçe": "Takip bilgilerini e-postayla gönder", "Deutsch": "Sendungsdaten per E-Mail senden", "Français": "Envoyer le suivi par e-mail", "Italiano": "Invia il tracciamento via e-mail", "Español (Spanish)": "Enviar seguimiento por correo", "Português": "Enviar rastreio por e-mail", "Русский (Russian)": "Отправить данные отслеживания по почте", "日本語 (Japanese)": "追跡情報をメールで送る", "中文 (Chinese)": "通过邮件发送追踪信息", "العربية (Arabic)": "إرسال بيانات التتبع بالبريد", "हिन्दी (Hindi)": "ट्रैकिंग जानकारी ई-मेल करें"},
  "Not sent: this number was already e-mailed.": {"Türkçe": "Gönderilmedi: bu numara zaten e-postayla gönderilmişti.", "Deutsch": "Nicht gesendet: Diese Nummer wurde bereits per E-Mail verschickt.", "Français": "Non envoyé : ce numéro a déjà été envoyé par e-mail.", "Italiano": "Non inviato: questo numero è già stato inviato via e-mail.", "Español (Spanish)": "No enviado: este número ya se envió por correo.", "Português": "Não enviado: este número já foi enviado por e-mail.", "Русский (Russian)": "Не отправлено: этот номер уже был отправлен по почте.", "日本語 (Japanese)": "送信されませんでした：この番号はすでにメール済みです。", "中文 (Chinese)": "未发送：此号码已通过邮件发送过。", "العربية (Arabic)": "لم يُرسَل: هذا الرقم أُرسل بالبريد من قبل.", "हिन्दी (Hindi)": "नहीं भेजा गया: यह नंबर पहले ही ई-मेल किया जा चुका है।"},
  "The e-mail could not be sent: {error}": {"Türkçe": "E-posta gönderilemedi: {error}", "Deutsch": "Die E-Mail konnte nicht gesendet werden: {error}", "Français": "L'e-mail n'a pas pu être envoyé : {error}", "Italiano": "Impossibile inviare l'e-mail: {error}", "Español (Spanish)": "No se pudo enviar el correo: {error}", "Português": "Não foi possível enviar o e-mail: {error}", "Русский (Russian)": "Не удалось отправить письмо: {error}", "日本語 (Japanese)": "メールを送信できませんでした：{error}", "中文 (Chinese)": "邮件无法发送：{error}", "العربية (Arabic)": "تعذّر إرسال الرسالة: {error}", "हिन्दी (Hindi)": "ई-मेल नहीं भेजा जा सका: {error}"},
  "Order reference": {"Türkçe": "Sipariş referansı", "Deutsch": "Bestellreferenz", "Français": "Référence de commande", "Italiano": "Riferimento ordine", "Español (Spanish)": "Referencia del pedido", "Português": "Referência da encomenda", "Русский (Russian)": "Номер заказа", "日本語 (Japanese)": "注文の参照番号", "中文 (Chinese)": "订单编号", "العربية (Arabic)": "مرجع الطلب", "हिन्दी (Hindi)": "ऑर्डर संदर्भ"},
  "Tracking number": {"Türkçe": "Takip numarası", "Deutsch": "Sendungsnummer", "Français": "Numéro de suivi", "Italiano": "Numero di tracciamento", "Español (Spanish)": "Número de seguimiento", "Português": "Número de rastreio", "Русский (Russian)": "Номер отслеживания", "日本語 (Japanese)": "追跡番号", "中文 (Chinese)": "追踪号码", "العربية (Arabic)": "رقم التتبع", "हिन्दी (Hindi)": "ट्रैकिंग नंबर"},
  "Tracking details by e-mail": {"Türkçe": "Takip bilgileri e-postası", "Deutsch": "Sendungsdaten per E-Mail", "Français": "Informations de suivi par e-mail", "Italiano": "Dettagli di tracciamento via e-mail", "Español (Spanish)": "Datos de seguimiento por correo", "Português": "Dados de rastreio por e-mail", "Русский (Russian)": "Данные отслеживания по почте", "日本語 (Japanese)": "追跡情報のメール", "中文 (Chinese)": "通过邮件发送追踪信息", "العربية (Arabic)": "بيانات التتبع بالبريد الإلكتروني", "हिन्दी (Hindi)": "ई-मेल से ट्रैकिंग जानकारी"},
  "Preparing the preview…": {"Türkçe": "Önizleme hazırlanıyor…", "Deutsch": "Vorschau wird vorbereitet …", "Français": "Préparation de l'aperçu…", "Italiano": "Preparazione dell'anteprima…", "Español (Spanish)": "Preparando la vista previa…", "Português": "A preparar a pré-visualização…", "Русский (Russian)": "Подготовка предпросмотра…", "日本語 (Japanese)": "プレビューを準備しています…", "中文 (Chinese)": "正在准备预览…", "العربية (Arabic)": "جارٍ تجهيز المعاينة…", "हिन्दी (Hindi)": "पूर्वावलोकन तैयार हो रहा है…"},
  "Could not prepare the e-mail preview.": {"Türkçe": "E-posta önizlemesi hazırlanamadı.", "Deutsch": "Die E-Mail-Vorschau konnte nicht erstellt werden.", "Français": "Impossible de préparer l'aperçu de l'e-mail.", "Italiano": "Impossibile preparare l'anteprima dell'e-mail.", "Español (Spanish)": "No se pudo preparar la vista previa del correo.", "Português": "Não foi possível preparar a pré-visualização do e-mail.", "Русский (Russian)": "Не удалось подготовить предпросмотр письма.", "日本語 (Japanese)": "メールのプレビューを準備できませんでした。", "中文 (Chinese)": "无法准备邮件预览。", "العربية (Arabic)": "تعذّر تجهيز معاينة الرسالة.", "हिन्दी (Hindi)": "ई-मेल का पूर्वावलोकन तैयार नहीं किया जा सका।"},
  "Tracking details e-mailed to {to} on {at}.": {"Türkçe": "Takip bilgileri {at} tarihinde {to} adresine e-postayla gönderildi.", "Deutsch": "Sendungsdaten am {at} per E-Mail an {to} gesendet.", "Français": "Informations de suivi envoyées par e-mail à {to} le {at}.", "Italiano": "Dettagli di tracciamento inviati via e-mail a {to} il {at}.", "Español (Spanish)": "Datos de seguimiento enviados por correo a {to} el {at}.", "Português": "Dados de rastreio enviados por e-mail para {to} em {at}.", "Русский (Russian)": "Данные отслеживания отправлены на {to} {at}.", "日本語 (Japanese)": "{at} に {to} へ追跡情報をメールで送信しました。", "中文 (Chinese)": "已于 {at} 将追踪信息通过邮件发送至 {to}。", "العربية (Arabic)": "أُرسلت بيانات التتبع بالبريد إلى {to} في {at}.", "हिन्दी (Hindi)": "ट्रैकिंग जानकारी {at} को {to} पर ई-मेल की गई।"},
  "Tracking e-mail to {to} failed on {at}: {error}": {"Türkçe": "{to} adresine takip e-postası {at} tarihinde gönderilemedi: {error}", "Deutsch": "Sendungs-E-Mail an {to} am {at} fehlgeschlagen: {error}", "Français": "L'e-mail de suivi à {to} a échoué le {at} : {error}", "Italiano": "E-mail di tracciamento a {to} non riuscita il {at}: {error}", "Español (Spanish)": "El correo de seguimiento a {to} falló el {at}: {error}", "Português": "O e-mail de rastreio para {to} falhou em {at}: {error}", "Русский (Russian)": "Письмо с отслеживанием на {to} не отправлено {at}: {error}", "日本語 (Japanese)": "{at} の {to} への追跡メールが失敗しました：{error}", "中文 (Chinese)": "{at} 发往 {to} 的追踪邮件失败：{error}", "العربية (Arabic)": "فشل إرسال رسالة التتبع إلى {to} في {at}: {error}", "हिन्दी (Hindi)": "{at} को {to} पर ट्रैकिंग ई-मेल विफल रहा: {error}"},
  "Already e-mailed to {to} on {at}. Sending again will deliver a second copy.": {"Türkçe": "{at} tarihinde {to} adresine zaten gönderildi. Yeniden gönderirseniz ikinci bir kopya ulaşır.", "Deutsch": "Bereits am {at} an {to} gesendet. Ein erneutes Senden liefert eine zweite Kopie.", "Français": "Déjà envoyé à {to} le {at}. Renvoyer livrera une seconde copie.", "Italiano": "Già inviato a {to} il {at}. Inviando di nuovo arriverà una seconda copia.", "Español (Spanish)": "Ya se envió a {to} el {at}. Si lo envías de nuevo llegará una segunda copia.", "Português": "Já enviado para {to} em {at}. Enviar de novo entregará uma segunda cópia.", "Русский (Russian)": "Уже отправлено на {to} {at}. Повторная отправка доставит вторую копию.", "日本語 (Japanese)": "{at} に {to} へ送信済みです。再送信すると2通目が届きます。", "中文 (Chinese)": "已于 {at} 发送至 {to}。再次发送将送达第二份副本。", "العربية (Arabic)": "أُرسل بالفعل إلى {to} في {at}. الإرسال مرة أخرى سيوصل نسخة ثانية.", "हिन्दी (Hindi)": "{at} को {to} पर पहले ही भेजा जा चुका है। दोबारा भेजने पर दूसरी प्रति पहुँचेगी।"},
  "This order has no customer e-mail address. Enter one here to send, or add it to the order first.": {"Türkçe": "Bu siparişte müşteri e-posta adresi yok. Göndermek için buraya bir adres girin ya da önce siparişe ekleyin.", "Deutsch": "Diese Bestellung hat keine Kunden-E-Mail-Adresse. Geben Sie hier eine ein oder tragen Sie sie zuerst in die Bestellung ein.", "Français": "Cette commande n'a pas d'adresse e-mail client. Saisissez-en une ici pour envoyer, ou ajoutez-la d'abord à la commande.", "Italiano": "Questo ordine non ha un indirizzo e-mail del cliente. Inseriscine uno qui per inviare, oppure aggiungilo prima all'ordine.", "Español (Spanish)": "Este pedido no tiene correo electrónico del cliente. Escribe uno aquí para enviar, o añádelo primero al pedido.", "Português": "Esta encomenda não tem e-mail do cliente. Introduza um aqui para enviar, ou adicione-o primeiro à encomenda.", "Русский (Russian)": "У этого заказа нет адреса электронной почты клиента. Введите его здесь или сначала добавьте в заказ.", "日本語 (Japanese)": "この注文にはお客様のメールアドレスがありません。ここに入力して送信するか、先に注文へ追加してください。", "中文 (Chinese)": "此订单没有客户电子邮件地址。请在此输入一个以发送，或先将其添加到订单。", "العربية (Arabic)": "لا يحتوي هذا الطلب على بريد إلكتروني للعميل. أدخل عنوانًا هنا للإرسال، أو أضفه إلى الطلب أولًا.", "हिन्दी (Hindi)": "इस ऑर्डर में ग्राहक का ई-मेल पता नहीं है। भेजने के लिए यहाँ एक पता डालें, या पहले उसे ऑर्डर में जोड़ें।"},
  "Enter a valid e-mail address.": {"Türkçe": "Geçerli bir e-posta adresi girin.", "Deutsch": "Geben Sie eine gültige E-Mail-Adresse ein.", "Français": "Saisissez une adresse e-mail valide.", "Italiano": "Inserisci un indirizzo e-mail valido.", "Español (Spanish)": "Introduce una dirección de correo válida.", "Português": "Introduza um endereço de e-mail válido.", "Русский (Russian)": "Введите корректный адрес электронной почты.", "日本語 (Japanese)": "有効なメールアドレスを入力してください。", "中文 (Chinese)": "请输入有效的电子邮件地址。", "العربية (Arabic)": "أدخل عنوان بريد إلكتروني صالحًا.", "हिन्दी (Hindi)": "एक मान्य ई-मेल पता डालें।"},
  "Reply-To": {"Türkçe": "Yanıt adresi", "Deutsch": "Antwort an", "Français": "Répondre à", "Italiano": "Rispondi a", "Español (Spanish)": "Responder a", "Português": "Responder para", "Русский (Russian)": "Адрес для ответа", "日本語 (Japanese)": "返信先", "中文 (Chinese)": "回复地址", "العربية (Arabic)": "الرد إلى", "हिन्दी (Hindi)": "उत्तर पता"},
  "Not set — add a reply-to address in Settings so the customer's reply reaches you.": {"Türkçe": "Ayarlanmamış — müşterinin yanıtı size ulaşsın diye Ayarlar'da bir yanıt adresi ekleyin.", "Deutsch": "Nicht gesetzt — hinterlegen Sie in den Einstellungen eine Antwortadresse, damit die Antwort des Kunden Sie erreicht.", "Français": "Non défini — ajoutez une adresse de réponse dans les Réglages pour que la réponse du client vous parvienne.", "Italiano": "Non impostato — aggiungi un indirizzo di risposta nelle Impostazioni perché la risposta del cliente ti raggiunga.", "Español (Spanish)": "Sin definir — añade una dirección de respuesta en Ajustes para que la respuesta del cliente te llegue.", "Português": "Não definido — adicione um endereço de resposta nas Definições para que a resposta do cliente lhe chegue.", "Русский (Russian)": "Не задан — укажите адрес для ответа в Настройках, чтобы ответ клиента дошёл до вас.", "日本語 (Japanese)": "未設定 — お客様の返信が届くよう、設定で返信先アドレスを追加してください。", "中文 (Chinese)": "未设置 — 请在设置中添加回复地址，以便客户的回复能送达您。", "العربية (Arabic)": "غير محدد — أضف عنوان ردّ في الإعدادات ليصلك ردّ العميل.", "हिन्दी (Hindi)": "सेट नहीं है — सेटिंग्स में उत्तर पता जोड़ें ताकि ग्राहक का जवाब आप तक पहुँचे।"},
  "Message": {"Français": "Message"},
  "A tracking number is not proof of dispatch: the message says the details appear once the carrier scans the parcel.": {"Türkçe": "Takip numarası kargoya verildiğinin kanıtı değildir: mesaj, bilgilerin kargo firması paketi taradığında görüneceğini söyler.", "Deutsch": "Eine Sendungsnummer ist kein Versandnachweis: Die Nachricht sagt, dass die Daten erscheinen, sobald der Versanddienstleister das Paket scannt.", "Français": "Un numéro de suivi n'est pas une preuve d'expédition : le message indique que les informations apparaissent une fois le colis scanné par le transporteur.", "Italiano": "Un numero di tracciamento non è prova di spedizione: il messaggio dice che i dettagli compaiono quando il corriere scansiona il pacco.", "Español (Spanish)": "Un número de seguimiento no es prueba de envío: el mensaje dice que los datos aparecen cuando el transportista escanea el paquete.", "Português": "Um número de rastreio não é prova de expedição: a mensagem diz que os dados aparecem quando a transportadora digitaliza o volume.", "Русский (Russian)": "Номер отслеживания — не доказательство отправки: в письме сказано, что данные появятся после сканирования посылки перевозчиком.", "日本語 (Japanese)": "追跡番号は発送の証明ではありません。メッセージには、配送業者が荷物をスキャンした後に情報が表示されると書かれています。", "中文 (Chinese)": "追踪号码并不证明已发货：邮件中说明信息会在承运商扫描包裹后显示。", "العربية (Arabic)": "رقم التتبع ليس دليلًا على الإرسال: تذكر الرسالة أن البيانات تظهر بعد أن تمسح شركة الشحن الطرد.", "हिन्दी (Hindi)": "ट्रैकिंग नंबर डिस्पैच का प्रमाण नहीं है: संदेश में लिखा है कि जानकारी कैरियर के पार्सल स्कैन करने के बाद दिखेगी।"},
  "Tracking link": {"Türkçe": "Takip bağlantısı", "Deutsch": "Sendungsverfolgungslink", "Français": "Lien de suivi", "Italiano": "Link di tracciamento", "Español (Spanish)": "Enlace de seguimiento", "Português": "Ligação de rastreio", "Русский (Russian)": "Ссылка для отслеживания", "日本語 (Japanese)": "追跡リンク", "中文 (Chinese)": "追踪链接", "العربية (Arabic)": "رابط التتبع", "हिन्दी (Hindi)": "ट्रैकिंग लिंक"},
  "17TRACK public page: this carrier is not in the link list.": {"Türkçe": "17TRACK genel sayfası: bu kargo firması bağlantı listesinde yok.", "Deutsch": "Öffentliche 17TRACK-Seite: Dieser Versanddienstleister steht nicht in der Linkliste.", "Français": "Page publique 17TRACK : ce transporteur n'est pas dans la liste des liens.", "Italiano": "Pagina pubblica 17TRACK: questo corriere non è nell'elenco dei link.", "Español (Spanish)": "Página pública de 17TRACK: este transportista no está en la lista de enlaces.", "Português": "Página pública da 17TRACK: esta transportadora não está na lista de ligações.", "Русский (Russian)": "Публичная страница 17TRACK: этого перевозчика нет в списке ссылок.", "日本語 (Japanese)": "17TRACK の公開ページ：この配送業者はリンク一覧にありません。", "中文 (Chinese)": "17TRACK 公共页面：此承运商不在链接列表中。", "العربية (Arabic)": "صفحة 17TRACK العامة: شركة الشحن هذه ليست في قائمة الروابط.", "हिन्दी (Hindi)": "17TRACK सार्वजनिक पृष्ठ: यह कैरियर लिंक सूची में नहीं है।"},
  "The link is built by NivaDesk from the tracking number; a typed link is never used.": {"Türkçe": "Bağlantıyı NivaDesk takip numarasından oluşturur; elle yazılan bir bağlantı asla kullanılmaz.", "Deutsch": "Der Link wird von NivaDesk aus der Sendungsnummer erzeugt; ein eingetippter Link wird nie verwendet.", "Français": "Le lien est construit par NivaDesk à partir du numéro de suivi ; un lien saisi à la main n'est jamais utilisé.", "Italiano": "Il link è generato da NivaDesk dal numero di tracciamento; un link digitato non viene mai usato.", "Español (Spanish)": "NivaDesk crea el enlace a partir del número de seguimiento; nunca se usa un enlace escrito a mano.", "Português": "A ligação é criada pelo NivaDesk a partir do número de rastreio; uma ligação escrita à mão nunca é usada.", "Русский (Russian)": "Ссылку NivaDesk формирует из номера отслеживания; введённая вручную ссылка никогда не используется.", "日本語 (Japanese)": "リンクは追跡番号から NivaDesk が生成します。手入力されたリンクは使用されません。", "中文 (Chinese)": "链接由 NivaDesk 根据追踪号码生成；绝不使用手动输入的链接。", "العربية (Arabic)": "يُنشئ NivaDesk الرابط من رقم التتبع؛ ولا يُستخدم أبدًا رابط مكتوب يدويًا.", "हिन्दी (Hindi)": "लिंक NivaDesk ट्रैकिंग नंबर से बनाता है; हाथ से लिखा लिंक कभी इस्तेमाल नहीं होता।"},
  "Send again": {"Türkçe": "Yeniden gönder", "Deutsch": "Erneut senden", "Français": "Envoyer à nouveau", "Italiano": "Invia di nuovo", "Español (Spanish)": "Enviar de nuevo", "Português": "Enviar novamente", "Русский (Russian)": "Отправить ещё раз", "日本語 (Japanese)": "もう一度送信", "中文 (Chinese)": "再次发送", "العربية (Arabic)": "إرسال مرة أخرى", "हिन्दी (Hindi)": "फिर से भेजें"},
  "Nothing is sent until you press Send.": {"Türkçe": "Gönder'e basana kadar hiçbir şey gönderilmez.", "Deutsch": "Es wird nichts gesendet, bis Sie auf Senden klicken.", "Français": "Rien n'est envoyé tant que vous n'appuyez pas sur Envoyer.", "Italiano": "Nulla viene inviato finché non premi Invia.", "Español (Spanish)": "No se envía nada hasta que pulses Enviar.", "Português": "Nada é enviado até carregar em Enviar.", "Русский (Russian)": "Ничего не отправляется, пока вы не нажмёте «Отправить».", "日本語 (Japanese)": "「送信」を押すまで何も送信されません。", "中文 (Chinese)": "在您按下“发送”之前不会发送任何内容。", "العربية (Arabic)": "لا يُرسَل شيء حتى تضغط على إرسال.", "हिन्दी (Hindi)": "जब तक आप भेजें नहीं दबाते, कुछ भी नहीं भेजा जाता।"}
};
